name: Custom Webhook Trigger

on:
  repository_dispatch:
    types: [custom-webhook-event]

jobs:
  process-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print event payload
        run: echo "Event payload: ${{ toJson(github.event.client_payload) }}"
